d3.select("body")
.append("svg")
.attr("width", 500)
.attr("height", 50)
.style("position", "absolute")
.append("rect")
.attr("x", 0)
.attr("y", 0)
.attr("width", 30)
.attr("height", 30)
.attr("fill", "purple");

d3.select("body")
.append("svg")
.attr("width", 500)
.attr("height", 50)
.style("position", "absolute")
.append("rect")
.attr("x", 20)
.attr("y", 5)
.attr("width", 30)
.attr("height", 30)
.attr("fill", "blue");

d3.select("body")
.append("svg")
.attr("width", 500)
.attr("height", 50)
.style("position", "absolute")
.append("rect")
.attr("x", 40)
.attr("y", 10)
.attr("width", 30)
.attr("height", 30)
.attr("fill", "green");

d3.select("body")
.append("svg")
.attr("width", 500)
.attr("height", 50)
.style("position", "absolute")
.append("rect")
.attr("x", 60)
.attr("y", 15)
.attr("width", 30)
.attr("height", 30)
.attr("fill", "yellow");

d3.select("body")
.append("svg")
.attr("width", 500)
.attr("height", 50)
.style("position", "absolute")
.append("rect")
.attr("x", 80)
.attr("y", 20)
.attr("width", 30)
.attr("height", 30)
.attr("fill", "red")
;
